import sys
import os
# Ensure Streamlit Cloud can find local modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import streamlit as st
import pandas as pd
import torch

from src.preprocessing import chunk_text, extract_speakers
from src.summarization import load_summarizer, summarize_text
from src.keywords import extract_keywords
from src.sentiment import load_sentiment_analyzer, analyze_sentiment, track_sentiment_over_time, load_emotion_analyzer, analyze_emotion
from src.ner import load_ner_model, extract_entities
from src.semantic import load_embedding_model, semantic_search
from src.behavior import analyze_behavior
from src.personality import detect_personality
from src.visualizations import generate_wordcloud

st.set_page_config(page_title="NLP Insights Dashboard", page_icon="🌌", layout="wide")

# Advanced Custom CSS for Rich Aesthetics
st.markdown("""
<style>
    .stApp {
        background-color: #0d1117;
        color: #c9d1d9;
        font-family: 'Inter', sans-serif;
    }
    .main-header {
        font-size: 3rem;
        font-weight: 800;
        background: -webkit-linear-gradient(45deg, #FF6B6B, #4ECDC4);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center;
        margin-bottom: 0;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #8b949e;
        text-align: center;
        margin-bottom: 2rem;
    }
    .stTextArea textarea {
        background-color: #161b22;
        color: #e6edf3;
        border: 1px solid #30363d;
        border-radius: 8px;
    }
    .metric-card {
        background: rgba(22, 27, 34, 0.8);
        border: 1px solid #30363d;
        border-radius: 12px;
        padding: 20px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.2);
        backdrop-filter: blur(10px);
        margin-bottom: 15px;
    }
    .metric-title {
        font-size: 1.1rem;
        color: #8b949e;
        margin-bottom: 10px;
    }
    .metric-value {
        font-size: 2rem;
        font-weight: 700;
        color: #58a6ff;
    }
    .trait-badge {
        display: inline-block;
        padding: 5px 15px;
        margin: 5px;
        border-radius: 20px;
        background: linear-gradient(90deg, #8a2be2, #4b0082);
        font-weight: bold;
        color: white;
        box-shadow: 0 2px 8px rgba(138,43,226, 0.4);
    }
</style>
""", unsafe_allow_html=True)

@st.cache_resource
def init_models():
    return {
        "summarizer": load_summarizer(),
        "sentiment": load_sentiment_analyzer(),
        "emotion": load_emotion_analyzer(),
        "ner": load_ner_model(),
        "embedder": load_embedding_model()
    }

def build_markdown_report(title, summary, overall_sent, behavior, entities, emotion_dist, speakers):
    """Builds a markdown string for the downloadable report."""
    md = f"# NLP Analysis Report: {title}\n\n"
    md += f"## 📝 Abstractive Summary\n{summary}\n\n"
    md += f"## 📊 Core Metrics\n"
    md += f"- **Sentiment:** {overall_sent['label']} ({(overall_sent['score']*100):.1f}%)\n"
    md += f"- **Sentences:** {behavior['total_sentences']}\n"
    md += f"- **Avg Words/Sentence:** {behavior['avg_words_per_sentence']}\n\n"
    
    if emotion_dist:
        md += "## 🎭 Emotion Distribution\n"
        for em, score in emotion_dist.items():
            md += f"- **{em.capitalize()}:** {(score*100):.1f}%\n"
        md += "\n"

    if entities:
        md += "## 📇 Named Entities\n"
        for k, v in entities.items():
            if v:
                md += f"**{k}**: {', '.join(v)}\n\n"

    if speakers:
        md += "## 🗣️ Transcript Speakers\n"
        md += f"Detected {len(speakers)} speakers: {', '.join(speakers.keys())}\n\n"
    
    md += "---\n*Generated by Deep Text Analytics*"
    return md

@st.cache_data(show_spinner=False)
def compute_analytics(text):
    models = init_models()
    # 1. Preprocessing
    chunks = chunk_text(text, max_words=300)
    
    # 2. Analytics
    sum_text = []
    for ch in chunks: # Summarize all chunks
        sum_text.append(summarize_text(models['summarizer'], ch))
    final_summary = " ".join(sum_text)
    
    # If the combined summary is very long, summarize the summary to keep it clean
    if len(chunks) > 2 and len(final_summary.split()) > 250:
        final_summary = summarize_text(models['summarizer'], final_summary)
    
    keywords = extract_keywords(text, top_n=8)
    overall_sent = analyze_sentiment(models['sentiment'], text)
    time_series = track_sentiment_over_time(models['sentiment'], text)
    emotion_dist = analyze_emotion(models['emotion'], text)
    entities = extract_entities(models['ner'], text)
    behavior = analyze_behavior(text)
    traits = detect_personality(overall_sent, behavior, keywords)
    speakers = extract_speakers(text)
    
    return final_summary, keywords, overall_sent, time_series, emotion_dist, entities, behavior, traits, speakers

def run_analysis(title, text):
    with st.spinner(f"Crunching data for {title}..."):
        final_summary, keywords, overall_sent, time_series, emotion_dist, entities, behavior, traits, speakers = compute_analytics(text)
    
    models = init_models()
    # UI Rendering
    
    # Download Button
    report_md = build_markdown_report(title, final_summary, overall_sent, behavior, entities, emotion_dist, speakers)
    st.download_button(
        label=f"📥 Download Report ({title})",
        data=report_md,
        file_name=f"{title.replace(' ', '_')}_report.md",
        mime="text/markdown"
    )
    
    # Row 1: Summary & Personality
    r1c1, r1c2 = st.columns(2)
    with r1c1:
        st.markdown("<div class='metric-card'>", unsafe_allow_html=True)
        st.markdown("<div class='metric-title'>📝 Abstractive Summary</div>", unsafe_allow_html=True)
        st.write(final_summary)
        st.markdown("</div>", unsafe_allow_html=True)
        
    with r1c2:
        st.markdown("<div class='metric-card'>", unsafe_allow_html=True)
        st.markdown("<div class='metric-title'>🎭 Personality & Tone</div>", unsafe_allow_html=True)
        traits_html = "".join([f"<span class='trait-badge'>{t}</span>" for t in traits])
        st.markdown(traits_html, unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        
    # Row 2: Metrics
    r2c1, r2c2, r2c3 = st.columns(3)
    with r2c1:
        st.markdown(f"<div class='metric-card'><div class='metric-title'>Sentiment Score</div><div class='metric-value' style='color: {'#3fb950' if overall_sent['label']=='POSITIVE' else '#f85149'}'>{overall_sent['label']} ({(overall_sent['score']*100):.1f}%)</div></div>", unsafe_allow_html=True)
    with r2c2:
        st.markdown(f"<div class='metric-card'><div class='metric-title'>Sentences</div><div class='metric-value'>{behavior['total_sentences']}</div></div>", unsafe_allow_html=True)
    with r2c3:
        st.markdown(f"<div class='metric-card'><div class='metric-title'>Avg Length</div><div class='metric-value'>{behavior['avg_words_per_sentence']} <span style='font-size:0.8rem;color:#8b949e'>words/sent</span></div></div>", unsafe_allow_html=True)
        
    # Row 3: Emotions and Word Cloud
    r3c1, r3c2 = st.columns(2)
    with r3c1:
        st.markdown("#### 🎭 Emotion Distribution")
        if emotion_dist:
            chart_data = pd.DataFrame(list(emotion_dist.values()), index=list(emotion_dist.keys()), columns=["Probability"])
            st.bar_chart(chart_data)
        else:
            st.info("No emotion data available.")
            
    with r3c2:
        st.markdown("#### ☁️ Theme Cloud")
        fig = generate_wordcloud(text)
        if fig:
            st.pyplot(fig)
        else:
            st.info("Not enough words to generate word cloud.")
        
    # Row 4: Keywords & Entities
    r4c1, r4c2 = st.columns(2)
    with r4c1:
        with st.expander("🔑 Contextual Keywords", expanded=True):
            st.write(", ".join(keywords))
    with r4c2:
        with st.expander("📇 Named Entities", expanded=True):
            for k, v in entities.items():
                if v:
                    st.write(f"**{k}**: {', '.join(v)}")

    # Row 5: Speakers
    if speakers:
        st.markdown("#### 🗣️ Transcript Analysis")
        cols = st.columns(min(len(speakers), 4)) # display up to 4 columns
        for idx, (speaker, speech) in enumerate(speakers.items()):
            with cols[idx % 4]:
                st.markdown(f"<div class='metric-card'><div class='metric-title'>Speaker</div><div class='metric-value' style='font-size:1.2rem'>{speaker} ({len(speech.split())} words)</div></div>", unsafe_allow_html=True)

    # Row 6: Sentiment over time & Semantic Search
    st.markdown("#### 📉 Emotional Intensity Map")
    if len(time_series) > 1:
        chart_data = pd.DataFrame(time_series, columns=["Sentiment Score"])
        st.line_chart(chart_data, color="#8a2be2")
    else:
        st.info("Not enough sentences to graph sentiment timeline.")
        
    st.markdown("#### 🔍 Semantic Smart Search")
    sq = st.text_input("Ask a question or search for a concept within this document...", key=f"search_{title}")
    if sq:
        results = semantic_search(models['embedder'], text, [sq], top_k=2)
        if results and sq in results:
            for i, res in enumerate(results[sq]):
                st.info(f"**Match {i+1}** (Score: {res['score']:.2f}): {res['sentence']}")

st.markdown('<div class="main-header">Deep Text Analytics</span></div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Upload or paste your conversation for an AI-powered behavioral dive</div>', unsafe_allow_html=True)

with st.spinner("Initializing AI engines... (Might take a moment on first load)"):
    models = init_models()

st.markdown("### 📥 Input Panel")
# Change to accept multiple files
uploaded_files = st.file_uploader("Upload .txt log files (Multiple allowed)", type=["txt"], accept_multiple_files=True)
input_text = st.text_area("Or Paste text here...", height=150)

analyze_btn = st.button("🚀 Analyze Now", use_container_width=True)

if analyze_btn:
    texts_to_process = []
    
    # Read inputs explicitly on button click
    if input_text.strip():
        texts_to_process.append(("Pasted Text", input_text))
        
    if uploaded_files:
        for uf in uploaded_files:
            file_text = uf.read().decode("utf-8")
            if file_text.strip():
                texts_to_process.append((uf.name, file_text))
                
    if texts_to_process:
        st.session_state['texts_to_process'] = texts_to_process
    else:
        st.session_state['texts_to_process'] = []
        st.warning("Please provide some text to analyze.")

# If data exists in state, render it so typing in search doesn't wipe it
if st.session_state.get('texts_to_process'):
    texts_to_process = st.session_state['texts_to_process']
    st.markdown("---")
    st.markdown("### 🧩 Analytical Insights")
    if len(texts_to_process) > 1:
        # Multi-document comparison using Tabs
        tabs = st.tabs([t[0] for t in texts_to_process])
        for idx, (title, text) in enumerate(texts_to_process):
            with tabs[idx]:
                run_analysis(title, text)
    else:
        run_analysis(texts_to_process[0][0], texts_to_process[0][1])
